### PR TITLE
Unicode support, settings updated correctly

### PR DESCRIPTION
**Pull request by pitaj**
Fixes related to regressions in #28

### CODE REVIEW

**Comment by julianlam** [comment]
Looks good to me, ready to publish @ninenine 😄

**Comment by ninenine** [comment]
@julianlam sorry about the revert I had been messing around with git on my local instance.
I'll update and publish.
@pitaj Thanks for the PR

**Comment by julianlam** [comment]
Did it need to be reverted?

**Comment by ninenine** [comment]
@julianlam nah that was my bad, wanted to set up a different branch to mess around with.

**Pull request merged**
